//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Spell
{
    public int Id { get; set; }
    public string SpellName { get; set; }
    public string SpellDescription { get; set; }
    public string SpellText { get; set; }
    public Nullable<int> SpellTypeId { get; set; }
    public string SpellAddedDescription { get; set; }

    public virtual SpellType SpellType { get; set; }
}
